# cargo-about is a tool to generate license compliance reports for Rust
# dependencies.
#
# Config reference: https://github.com/EmbarkStudios/cargo-about#configuration
#
# Common tasks
#
# - Generate a license report: cargo about generate about.hbs
# - Check license compliance:  cargo about check
#
accepted = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "MPL-2.0",
    "BSD-3-Clause",
    "ISC",
]

targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
private = { ignore = true }
